package com.zenkronn.project.datamodel;

// default package
// Generated Dec 12, 2017 10:26:42 PM by Hibernate Tools 5.2.6.Final

/**
 * AplUser generated by hbm2java
 */
public class AplUser implements java.io.Serializable {

	private Integer id;
	private String userName;
	private String password;
	private byte enabled;

	public AplUser() {
	}

	public AplUser(String userName, String password, byte enabled) {
		this.userName = userName;
		this.password = password;
		this.enabled = enabled;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public byte getEnabled() {
		return this.enabled;
	}

	public void setEnabled(byte enabled) {
		this.enabled = enabled;
	}

}
