package com.zenkronn.project.datamodel;

// default package
// Generated Dec 13, 2017 10:39:14 AM by Hibernate Tools 5.2.6.Final

import java.util.Date;

/**
 * CrossTable generated by hbm2java
 */
public class CrossTable implements java.io.Serializable {

	private Integer id;
	private Integer aplUserId;
	private Integer membersId;
	private Date friendshipDate;

	public CrossTable() {
	}

	public CrossTable(Date friendshipDate) {
		this.friendshipDate = friendshipDate;
	}

	public CrossTable(Integer aplUserId, Integer membersId, Date friendshipDate) {
		this.aplUserId = aplUserId;
		this.membersId = membersId;
		this.friendshipDate = friendshipDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getAplUserId() {
		return this.aplUserId;
	}

	public void setAplUserId(Integer aplUserId) {
		this.aplUserId = aplUserId;
	}

	public Integer getMembersId() {
		return this.membersId;
	}

	public void setMembersId(Integer membersId) {
		this.membersId = membersId;
	}

	public Date getFriendshipDate() {
		return this.friendshipDate;
	}

	public void setFriendshipDate(Date friendshipDate) {
		this.friendshipDate = friendshipDate;
	}

}
